openapi: 3.0.3
servers:
- url: http://localhost:2080/
  description: url Local
- url: https://dev.nttdata.com/msphone/
  description: url Desarrollo
- url: https://nttdata.com/msphone/
  description: url Produccion